Completed css-canvas-medical exercise. - Davin Phuong
dn-phuong/c0122-code-solutions pull request #32
Opened 2022-02-06 02:38 UTC by dn-phuong

![css-canvas-medical](https://user-images.githubusercontent.com/93227069/152665764-3fb9df54-5bb4-4509-9bd8-4f01e7e780df.png)

2022-02-07 18:41 UTC, codingcodymiller requested changes
Hey Davin! Your "Get Started" button seems to be vertically misaligned with the "Ready to learn more?" text section, and the final row with the two anchor links is too short as compared to the example, please revise and submit a new screenshot with your revision.

2022-02-09 06:22 UTC, dn-phuong commented
![css-canvas-medical 2](https://user-images.githubusercontent.com/93227069/153133601-95a3cfc7-a55f-434a-bdc7-8ccc7c91be77.png)

2022-02-09 15:32 UTC, thebearingedge requested changes

2022-02-10 04:27 UTC, dn-phuong commented
<img width="1284" alt="Screen Shot 2022-02-09 at 8 24 47 PM" src="https://user-images.githubusercontent.com/93227069/153337087-e90fd44f-e488-45e5-aaa7-0755cb960eb6.png">

2022-02-10 16:41 UTC, thebearingedge requested changes
No rush on this, we just want to avoid overusing positioning.

2022-02-10 16:41 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +
Try doing this without positioning the text, heading, or button. Instead, try putting them inside of the overlay and using padding to push them inward from the edges of the overlay.

2022-02-20 20:16 UTC, thebearingedge approved these changes

2022-02-21 00:26 UTC, merged