Completed javascript-loops-practice. - Davin Phuong
dn-phuong/c0122-code-solutions pull request #35
Opened 2022-02-06 07:05 UTC by dn-phuong

<img width="473" alt="Screen Shot 2022-02-05 at 11 02 36 PM" src="https://user-images.githubusercontent.com/93227069/152670957-7a117332-dbe7-4f2d-b96b-5e4ef8e911f7.png">

2022-02-07 18:28 UTC, codingcodymiller requested changes

2022-02-07 18:28 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    suffixArray.push(words[i] += suffix);
This is making a change to the original array, which is not good. Instead, you should just use that original array to generate the new values, but leave the original intact.

2022-02-07 18:28 UTC, codingcodymiller commented on javascript-loops-practice/filter-out-strings.js
> +    if (typeof values[i] === 'number') {
THis function. is meant to filter out strings, not keep all number values. What if there were more data types than numbers intermixed with the strings, like booleans or null?

2022-02-07 18:28 UTC, codingcodymiller commented on javascript-loops-practice/odd-or-even.js
> +      numbers[i] = 'odd';
This is making a change to the original array, which is not good. Instead, you should just use that original array to generate the new values, but leave the original intact.

2022-02-09 15:51 UTC, thebearingedge approved these changes

2022-02-09 18:07 UTC, merged