Completed javascript-and-json. - Davin Phuong
dn-phuong/c0122-code-solutions pull request #50
Opened 2022-02-11 22:52 UTC by dn-phuong

<img width="474" alt="Screen Shot 2022-02-11 at 2 51 13 PM" src="https://user-images.githubusercontent.com/93227069/153681426-d2c49064-aa8b-4d17-b9a0-0af4918ffadc.png">

2022-02-12 06:47 UTC, dn-phuong commented
<img width="423" alt="Screen Shot 2022-02-11 at 10 45 03 PM" src="https://user-images.githubusercontent.com/93227069/153700478-83806a01-99b1-4e1a-a9dc-a712c901c1ee.png">

2022-02-14 03:16 UTC, thebearingedge requested changes

2022-02-14 03:16 UTC, thebearingedge commented on javascript-and-json/main.js
> +var parsedObject = JSON.parse(JSON.stringify(studentJsonString));
Try only parsing your JSON now that it's a proper string.

2022-02-14 04:30 UTC, dn-phuong commented
<img width="429" alt="Screen Shot 2022-02-13 at 8 27 24 PM" src="https://user-images.githubusercontent.com/93227069/153800265-d3b042f0-7d1d-45c0-bb40-49c131feeb2d.png">

2022-02-14 15:21 UTC, thebearingedge approved these changes

2022-02-19 23:00 UTC, merged